# This rule is not used by the project ntn-operators itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over ntncellconfigs resources and read-only
# access to ntncellconfigs/status. This role is intended for cluster admins
# managing NTNCellConfig resources.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ntn-operators
    app.kubernetes.io/managed-by: kustomize
  name: ntncellconfig-admin-role
rules:
- apiGroups:
  - ntn.operators.dev
  resources:
  - ntncellconfigs
  verbs:
  - '*'
- apiGroups:
  - ntn.operators.dev
  resources:
  - ntncellconfigs/status
  verbs:
  - get
