//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BillingSpec) DeepCopyInto(out *BillingSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BillingSpec.
func (in *BillingSpec) DeepCopy() *BillingSpec {
	if in == nil {
		return nil
	}
	out := new(BillingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CellOverrides) DeepCopyInto(out *CellOverrides) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CellOverrides.
func (in *CellOverrides) DeepCopy() *CellOverrides {
	if in == nil {
		return nil
	}
	out := new(CellOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentSpec) DeepCopyInto(out *DeploymentSpec) {
	*out = *in
	out.Location = in.Location
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentSpec.
func (in *DeploymentSpec) DeepCopy() *DeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(DeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EphemerisECEF) DeepCopyInto(out *EphemerisECEF) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EphemerisECEF.
func (in *EphemerisECEF) DeepCopy() *EphemerisECEF {
	if in == nil {
		return nil
	}
	out := new(EphemerisECEF)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EphemerisSource) DeepCopyInto(out *EphemerisSource) {
	*out = *in
	out.RefreshInterval = in.RefreshInterval
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = new(SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EphemerisSource.
func (in *EphemerisSource) DeepCopy() *EphemerisSource {
	if in == nil {
		return nil
	}
	out := new(EphemerisSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailoverPolicy) DeepCopyInto(out *FailoverPolicy) {
	*out = *in
	if in.Triggers != nil {
		in, out := &in.Triggers, &out.Triggers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.SwitchbackDelay = in.SwitchbackDelay
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailoverPolicy.
func (in *FailoverPolicy) DeepCopy() *FailoverPolicy {
	if in == nil {
		return nil
	}
	out := new(FailoverPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirmwareSpec) DeepCopyInto(out *FirmwareSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirmwareSpec.
func (in *FirmwareSpec) DeepCopy() *FirmwareSpec {
	if in == nil {
		return nil
	}
	out := new(FirmwareSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeoLocation) DeepCopyInto(out *GeoLocation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeoLocation.
func (in *GeoLocation) DeepCopy() *GeoLocation {
	if in == nil {
		return nil
	}
	out := new(GeoLocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroundStationLifecycle) DeepCopyInto(out *GroundStationLifecycle) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroundStationLifecycle.
func (in *GroundStationLifecycle) DeepCopy() *GroundStationLifecycle {
	if in == nil {
		return nil
	}
	out := new(GroundStationLifecycle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GroundStationLifecycle) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroundStationLifecycleList) DeepCopyInto(out *GroundStationLifecycleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GroundStationLifecycle, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroundStationLifecycleList.
func (in *GroundStationLifecycleList) DeepCopy() *GroundStationLifecycleList {
	if in == nil {
		return nil
	}
	out := new(GroundStationLifecycleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GroundStationLifecycleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroundStationLifecycleSpec) DeepCopyInto(out *GroundStationLifecycleSpec) {
	*out = *in
	in.Hardware.DeepCopyInto(&out.Hardware)
	out.Deployment = in.Deployment
	if in.Monitoring != nil {
		in, out := &in.Monitoring, &out.Monitoring
		*out = new(MonitoringSpec)
		**out = **in
	}
	if in.Firmware != nil {
		in, out := &in.Firmware, &out.Firmware
		*out = new(FirmwareSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroundStationLifecycleSpec.
func (in *GroundStationLifecycleSpec) DeepCopy() *GroundStationLifecycleSpec {
	if in == nil {
		return nil
	}
	out := new(GroundStationLifecycleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroundStationLifecycleStatus) DeepCopyInto(out *GroundStationLifecycleStatus) {
	*out = *in
	if in.LastHealthCheck != nil {
		in, out := &in.LastHealthCheck, &out.LastHealthCheck
		*out = (*in).DeepCopy()
	}
	if in.FirmwareUpdateStarted != nil {
		in, out := &in.FirmwareUpdateStarted, &out.FirmwareUpdateStarted
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroundStationLifecycleStatus.
func (in *GroundStationLifecycleStatus) DeepCopy() *GroundStationLifecycleStatus {
	if in == nil {
		return nil
	}
	out := new(GroundStationLifecycleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HardwareSpec) DeepCopyInto(out *HardwareSpec) {
	*out = *in
	if in.Bands != nil {
		in, out := &in.Bands, &out.Bands
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HardwareSpec.
func (in *HardwareSpec) DeepCopy() *HardwareSpec {
	if in == nil {
		return nil
	}
	out := new(HardwareSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringSpec) DeepCopyInto(out *MonitoringSpec) {
	*out = *in
	out.HealthCheckInterval = in.HealthCheckInterval
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringSpec.
func (in *MonitoringSpec) DeepCopy() *MonitoringSpec {
	if in == nil {
		return nil
	}
	out := new(MonitoringSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MovingRefLocation) DeepCopyInto(out *MovingRefLocation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MovingRefLocation.
func (in *MovingRefLocation) DeepCopy() *MovingRefLocation {
	if in == nil {
		return nil
	}
	out := new(MovingRefLocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NTNCellConfig) DeepCopyInto(out *NTNCellConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NTNCellConfig.
func (in *NTNCellConfig) DeepCopy() *NTNCellConfig {
	if in == nil {
		return nil
	}
	out := new(NTNCellConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NTNCellConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NTNCellConfigList) DeepCopyInto(out *NTNCellConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NTNCellConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NTNCellConfigList.
func (in *NTNCellConfigList) DeepCopy() *NTNCellConfigList {
	if in == nil {
		return nil
	}
	out := new(NTNCellConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NTNCellConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NTNCellConfigSpec) DeepCopyInto(out *NTNCellConfigSpec) {
	*out = *in
	out.Provider = in.Provider
	in.NTN.DeepCopyInto(&out.NTN)
	if in.CellOverrides != nil {
		in, out := &in.CellOverrides, &out.CellOverrides
		*out = new(CellOverrides)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NTNCellConfigSpec.
func (in *NTNCellConfigSpec) DeepCopy() *NTNCellConfigSpec {
	if in == nil {
		return nil
	}
	out := new(NTNCellConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NTNCellConfigStatus) DeepCopyInto(out *NTNCellConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NTNCellConfigStatus.
func (in *NTNCellConfigStatus) DeepCopy() *NTNCellConfigStatus {
	if in == nil {
		return nil
	}
	out := new(NTNCellConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NTNParams) DeepCopyInto(out *NTNParams) {
	*out = *in
	if in.TAInfo != nil {
		in, out := &in.TAInfo, &out.TAInfo
		*out = new(TAInfo)
		**out = **in
	}
	out.EphemerisECEF = in.EphemerisECEF
	if in.MovingRefLocation != nil {
		in, out := &in.MovingRefLocation, &out.MovingRefLocation
		*out = new(MovingRefLocation)
		**out = **in
	}
	if in.SatSwitchWithResync != nil {
		in, out := &in.SatSwitchWithResync, &out.SatSwitchWithResync
		*out = new(SatSwitchWithResync)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NTNParams.
func (in *NTNParams) DeepCopy() *NTNParams {
	if in == nil {
		return nil
	}
	out := new(NTNParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NTNSlice) DeepCopyInto(out *NTNSlice) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NTNSlice.
func (in *NTNSlice) DeepCopy() *NTNSlice {
	if in == nil {
		return nil
	}
	out := new(NTNSlice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NTNSlice) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NTNSliceList) DeepCopyInto(out *NTNSliceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NTNSlice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NTNSliceList.
func (in *NTNSliceList) DeepCopy() *NTNSliceList {
	if in == nil {
		return nil
	}
	out := new(NTNSliceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NTNSliceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NTNSliceSpec) DeepCopyInto(out *NTNSliceSpec) {
	*out = *in
	out.TerrestrialPath = in.TerrestrialPath
	out.SatellitePath = in.SatellitePath
	in.FailoverPolicy.DeepCopyInto(&out.FailoverPolicy)
	if in.QoSMapping != nil {
		in, out := &in.QoSMapping, &out.QoSMapping
		*out = new(QoSMapping)
		**out = **in
	}
	if in.Security != nil {
		in, out := &in.Security, &out.Security
		*out = new(SecurityPolicy)
		**out = **in
	}
	if in.Billing != nil {
		in, out := &in.Billing, &out.Billing
		*out = new(BillingSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NTNSliceSpec.
func (in *NTNSliceSpec) DeepCopy() *NTNSliceSpec {
	if in == nil {
		return nil
	}
	out := new(NTNSliceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NTNSliceStatus) DeepCopyInto(out *NTNSliceStatus) {
	*out = *in
	if in.LastFailover != nil {
		in, out := &in.LastFailover, &out.LastFailover
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NTNSliceStatus.
func (in *NTNSliceStatus) DeepCopy() *NTNSliceStatus {
	if in == nil {
		return nil
	}
	out := new(NTNSliceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PassPredictionSpec) DeepCopyInto(out *PassPredictionSpec) {
	*out = *in
	if in.GroundStations != nil {
		in, out := &in.GroundStations, &out.GroundStations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Horizon = in.Horizon
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PassPredictionSpec.
func (in *PassPredictionSpec) DeepCopy() *PassPredictionSpec {
	if in == nil {
		return nil
	}
	out := new(PassPredictionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PassWindow) DeepCopyInto(out *PassWindow) {
	*out = *in
	in.AOS.DeepCopyInto(&out.AOS)
	in.LOS.DeepCopyInto(&out.LOS)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PassWindow.
func (in *PassWindow) DeepCopy() *PassWindow {
	if in == nil {
		return nil
	}
	out := new(PassWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PathSpec) DeepCopyInto(out *PathSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PathSpec.
func (in *PathSpec) DeepCopy() *PathSpec {
	if in == nil {
		return nil
	}
	out := new(PathSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderRef) DeepCopyInto(out *ProviderRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderRef.
func (in *ProviderRef) DeepCopy() *ProviderRef {
	if in == nil {
		return nil
	}
	out := new(ProviderRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QoSMapping) DeepCopyInto(out *QoSMapping) {
	*out = *in
	out.MaxLatencyBudget = in.MaxLatencyBudget
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QoSMapping.
func (in *QoSMapping) DeepCopy() *QoSMapping {
	if in == nil {
		return nil
	}
	out := new(QoSMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SatSwitchWithResync) DeepCopyInto(out *SatSwitchWithResync) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SatSwitchWithResync.
func (in *SatSwitchWithResync) DeepCopy() *SatSwitchWithResync {
	if in == nil {
		return nil
	}
	out := new(SatSwitchWithResync)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SatelliteEphemeris) DeepCopyInto(out *SatelliteEphemeris) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SatelliteEphemeris.
func (in *SatelliteEphemeris) DeepCopy() *SatelliteEphemeris {
	if in == nil {
		return nil
	}
	out := new(SatelliteEphemeris)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SatelliteEphemeris) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SatelliteEphemerisList) DeepCopyInto(out *SatelliteEphemerisList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SatelliteEphemeris, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SatelliteEphemerisList.
func (in *SatelliteEphemerisList) DeepCopy() *SatelliteEphemerisList {
	if in == nil {
		return nil
	}
	out := new(SatelliteEphemerisList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SatelliteEphemerisList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SatelliteEphemerisSpec) DeepCopyInto(out *SatelliteEphemerisSpec) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	if in.Satellites != nil {
		in, out := &in.Satellites, &out.Satellites
		*out = new(SatelliteSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.PassPrediction != nil {
		in, out := &in.PassPrediction, &out.PassPrediction
		*out = new(PassPredictionSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SatelliteEphemerisSpec.
func (in *SatelliteEphemerisSpec) DeepCopy() *SatelliteEphemerisSpec {
	if in == nil {
		return nil
	}
	out := new(SatelliteEphemerisSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SatelliteEphemerisStatus) DeepCopyInto(out *SatelliteEphemerisStatus) {
	*out = *in
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = (*in).DeepCopy()
	}
	if in.NextPassWindows != nil {
		in, out := &in.NextPassWindows, &out.NextPassWindows
		*out = make([]PassWindow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SatelliteEphemerisStatus.
func (in *SatelliteEphemerisStatus) DeepCopy() *SatelliteEphemerisStatus {
	if in == nil {
		return nil
	}
	out := new(SatelliteEphemerisStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SatellitePathSpec) DeepCopyInto(out *SatellitePathSpec) {
	*out = *in
	out.PathSpec = in.PathSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SatellitePathSpec.
func (in *SatellitePathSpec) DeepCopy() *SatellitePathSpec {
	if in == nil {
		return nil
	}
	out := new(SatellitePathSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SatelliteSelector) DeepCopyInto(out *SatelliteSelector) {
	*out = *in
	if in.NoradIDs != nil {
		in, out := &in.NoradIDs, &out.NoradIDs
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SatelliteSelector.
func (in *SatelliteSelector) DeepCopy() *SatelliteSelector {
	if in == nil {
		return nil
	}
	out := new(SatelliteSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityPolicy) DeepCopyInto(out *SecurityPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityPolicy.
func (in *SecurityPolicy) DeepCopy() *SecurityPolicy {
	if in == nil {
		return nil
	}
	out := new(SecurityPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TAInfo) DeepCopyInto(out *TAInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TAInfo.
func (in *TAInfo) DeepCopy() *TAInfo {
	if in == nil {
		return nil
	}
	out := new(TAInfo)
	in.DeepCopyInto(out)
	return out
}
