/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package ocudu

import (
	"bytes"
	"fmt"
	"strconv"
	"strings"
	"text/template"

	ntnv1alpha1 "github.com/thc1006/ntn-operators/api/v1alpha1"
)

// yamlQuote emits a YAML 1.2 double-quoted string using Go's strconv.Quote.
// JSON-style double-quoted strings are a valid subset of YAML 1.2 scalars;
// newlines, colons, and other YAML-significant chars are escaped, preventing
// string injection from bleeding into the surrounding YAML structure even
// if apiserver enum validation is somehow bypassed (webhook misconfig,
// direct etcd write during migration, apiserver with --feature-gates=
// CRDValidation=false).
func yamlQuote(s string) string {
	return strconv.Quote(s)
}

// sanitizeComment strips characters that would terminate a YAML comment line
// (LF, CR, NEL, LS, PS, and NUL) so a user-supplied value cannot inject real
// YAML keys via the `# Payload type: ...` header line. Comments are
// line-terminated so quoting does not protect them.
func sanitizeComment(s string) string {
	r := strings.NewReplacer(
		"\n", " ",
		"\r", " ",
		"\u0085", " ",
		"\u2028", " ",
		"\u2029", " ",
		"\x00", "",
	)
	return r.Replace(s)
}

// configTemplate generates OCUDU-compatible NTN configuration YAML.
//
// This format was validated against OCUDU gNB (migrated from srsRAN_Project).
// Key format differences from the old docs-era geo_ntn.yml:
//   - ta_common is under ntn.ta_info (not ntn.ta_common)
//   - ephemeris uses ephemeris_info_ecef or ephemeris_orbital (variant)
//   - sib_mapping is scalar 19 (not array [19])
//   - si_window_position is REQUIRED for SIB19
//   - pucch.sr_period_ms is omitted (let gNB use bandwidth-appropriate default)
const configTemplate = `# Generated by NTN K8s Operators — do not edit manually
# Payload type: {{ .PayloadType }} (3GPP Rel-19: transparent or regenerative)

ntn:
  cell_specific_koffset: {{ .Koffset }}
  ta_info:
    ta_common: {{ .TACommon }}
{{- if .TAInfoExtended }}
    ta_common_drift: {{ .TACommonDrift }}
    ta_common_drift_variant: {{ .TACommonDriftVariant }}
    ta_common_offset: {{ .TACommonOffset }}
{{- end }}
{{- if .UseOrbital }}
  ephemeris_orbital:
    semi_major_axis: {{ .OrbSemiMajorAxis }}
    eccentricity: {{ .OrbEccentricity }}
    inclination: {{ .OrbInclination }}
    right_ascension: {{ .OrbRightAscension }}
    arg_of_periapsis: {{ .OrbArgOfPeriapsis }}
    mean_anomaly: {{ .OrbMeanAnomaly }}
{{- else }}
  ephemeris_info_ecef:
    pos_x: {{ .EphPosX }}
    pos_y: {{ .EphPosY }}
    pos_z: {{ .EphPosZ }}
    vel_x: {{ .EphVelX }}
    vel_y: {{ .EphVelY }}
    vel_z: {{ .EphVelZ }}
{{- end }}
{{- if .EpochTime }}
  epoch_time:
    sfn: {{ .EpochSFN }}
    subframe_number: {{ .EpochSubframeNumber }}
{{- end }}
{{- if .FeederLink }}
  feeder_link_info:
    enable_doppler_compensation: {{ .FeederDopplerCompensation }}
    dl_freq: {{ .FeederDLFreq }}
    ul_freq: {{ .FeederULFreq }}
{{- end }}
{{- if .GatewayLocation }}
  ntn_gateway_location:
    latitude: {{ .GatewayLatitude }}
    longitude: {{ .GatewayLongitude }}
    altitude: {{ .GatewayAltitude }}
{{- end }}
{{- if .HasNCells }}
  ncells:
{{- range .NCells }}
    - phys_cell_id: {{ .PhysicalCellID }}
{{- if .Frequency }}
      frequency: {{ .Frequency }}
{{- end }}
{{- end }}
{{- end }}
{{- if .HasReferenceLocation }}
  reference_location:
    latitude: {{ .RefLatitude }}
    longitude: {{ .RefLongitude }}
{{- end }}
{{- if .HasDistanceThreshold }}
  distance_threshold: {{ .DistanceThreshold }}
{{- end }}
{{- if .HasTService }}
  t_service: {{ .TService }}
{{- end }}
{{- if .MovingRefLocation }}
  moving_ref_location:
    latitude: {{ .MovingRefLatitude }}
    longitude: {{ .MovingRefLongitude }}
{{- end }}
{{- if .SatSwitchWithResync }}
  sat_switch_with_resync:
    target_pci: {{ .SatSwitchTargetPCI }}
    t304: {{ .SatSwitchT304 }}
{{- end }}
{{- if .HasPolarization }}
  polarization:
{{- if .PolarizationDL }}
    dl: {{ yamlQuote .PolarizationDL }}
{{- end }}
{{- if .PolarizationUL }}
    ul: {{ yamlQuote .PolarizationUL }}
{{- end }}
{{- end }}
{{- if .TAReportSet }}
  ta_report: {{ .TAReport }}
{{- end }}
{{- if .UlSyncValidityDurSet }}
  ntn_ul_sync_validity_dur: {{ .UlSyncValidityDur }}
{{- end }}

cell_cfg:
  sib:
    si_window_length: {{ .SIWindowLength }}
    si_sched_info:
      - si_period: {{ .SIPeriod }}
        sib_mapping: 19
        si_window_position: {{ .SIWindowPosition }}
  pdsch:
    max_nof_harq_retxs: {{ .PdschMaxHarqRetxs }}
  prach:
    max_msg3_harq_retx: {{ .PrachMaxMsg3HarqRetx }}

cu_cp:
  rrc:
    rrc_procedure_guard_time_ms: {{ .RrcGuardTimeMs }}
`

var parsedTemplate = template.Must(
	template.New("ocudu-ntn").
		Funcs(template.FuncMap{"yamlQuote": yamlQuote}).
		Parse(configTemplate),
)

// ntnNeighborCellData holds per-neighbor data for template rendering.
type ntnNeighborCellData struct {
	PhysicalCellID int
	Frequency      int
}

type configData struct {
	PayloadType               string
	Koffset                   int
	TACommon                  int
	TAInfoExtended            bool
	TACommonDrift             int
	TACommonDriftVariant      int
	TACommonOffset            int
	UseOrbital                bool
	EphPosX                   int
	EphPosY                   int
	EphPosZ                   int
	EphVelX                   int
	EphVelY                   int
	EphVelZ                   int
	OrbSemiMajorAxis          int
	OrbEccentricity           int
	OrbInclination            int
	OrbRightAscension         int
	OrbArgOfPeriapsis         int
	OrbMeanAnomaly            int
	EpochTime                 bool
	EpochSFN                  int
	EpochSubframeNumber       int
	FeederLink                bool
	FeederDopplerCompensation bool
	FeederDLFreq              int64
	FeederULFreq              int64
	GatewayLocation           bool
	GatewayLatitude           int
	GatewayLongitude          int
	GatewayAltitude           int
	HasNCells                 bool
	NCells                    []ntnNeighborCellData
	HasReferenceLocation      bool
	RefLatitude               int
	RefLongitude              int
	HasDistanceThreshold      bool
	DistanceThreshold         int
	HasTService               bool
	TService                  int
	MovingRefLocation         bool
	MovingRefLatitude         int
	MovingRefLongitude        int
	SatSwitchWithResync       bool
	SatSwitchTargetPCI        int
	SatSwitchT304             int
	HasPolarization           bool
	PolarizationDL            string
	PolarizationUL            string
	TAReportSet               bool
	TAReport                  bool
	UlSyncValidityDurSet      bool
	UlSyncValidityDur         int
	PdschMaxHarqRetxs         int
	PrachMaxMsg3HarqRetx      int
	RrcGuardTimeMs            int
	SIWindowLength            int
	SIPeriod                  int
	SIWindowPosition          int
}

// SI scheduling defaults mirror the live-gNB-verified geo_ntn.yml values.
const (
	defaultSIWindowLength   = 5
	defaultSIPeriod         = 16
	defaultSIWindowPosition = 1
)

// GenerateConfig produces OCUDU-compatible NTN configuration YAML
// from an NTNCellConfigSpec. The output matches the CLI11 config format
// accepted by OCUDU gNB (CLI11 config format).
func GenerateConfig(spec *ntnv1alpha1.NTNCellConfigSpec) ([]byte, error) {
	if spec == nil {
		return nil, fmt.Errorf("spec must not be nil")
	}

	data := baseConfigData(spec)
	applyTAInfo(&data, spec)
	applyOptionalNTNFields(&data, spec)
	applyStage3Fields(&data, spec)
	applyCellOverrides(&data, spec)
	if err := applyEphemeris(&data, spec); err != nil {
		return nil, err
	}

	var buf bytes.Buffer
	if err := parsedTemplate.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("executing config template: %w", err)
	}

	return buf.Bytes(), nil
}

func baseConfigData(spec *ntnv1alpha1.NTNCellConfigSpec) configData {
	payloadType := spec.NTN.PayloadType
	if payloadType == "" {
		payloadType = "transparent"
	}
	// Sanitize the comment-bound string so a malicious payload cannot break
	// out of the `# Payload type: ...` header into real YAML keys even if
	// apiserver enum validation were bypassed.
	payloadType = sanitizeComment(payloadType)

	return configData{
		PayloadType:          payloadType,
		Koffset:              spec.NTN.CellSpecificKoffset,
		TACommon:             spec.NTN.TACommon,
		PdschMaxHarqRetxs:    0,
		PrachMaxMsg3HarqRetx: 0,
		RrcGuardTimeMs:       12800,
		SIWindowLength:       defaultSIWindowLength,
		SIPeriod:             defaultSIPeriod,
		SIWindowPosition:     defaultSIWindowPosition,
	}
}

func applyTAInfo(data *configData, spec *ntnv1alpha1.NTNCellConfigSpec) {
	if spec.NTN.TAInfo == nil {
		return
	}

	ta := spec.NTN.TAInfo
	data.TACommon = ta.TACommon

	// Emit drift/offset sub-fields only when at least one is non-zero.
	if ta.TACommonDrift != 0 || ta.TACommonDriftVariant != 0 || ta.TACommonOffset != 0 {
		data.TAInfoExtended = true
		data.TACommonDrift = ta.TACommonDrift
		data.TACommonDriftVariant = ta.TACommonDriftVariant
		data.TACommonOffset = ta.TACommonOffset
	}
}

func applyOptionalNTNFields(data *configData, spec *ntnv1alpha1.NTNCellConfigSpec) {
	if spec.NTN.EpochTime != nil {
		data.EpochTime = true
		data.EpochSFN = spec.NTN.EpochTime.SFN
		data.EpochSubframeNumber = spec.NTN.EpochTime.SubframeNumber
	}
	if spec.NTN.FeederLinkInfo != nil {
		data.FeederLink = true
		data.FeederDopplerCompensation = spec.NTN.FeederLinkInfo.EnableDopplerCompensation
		data.FeederDLFreq = spec.NTN.FeederLinkInfo.DLFreqHz
		data.FeederULFreq = spec.NTN.FeederLinkInfo.ULFreqHz
	}
	if spec.NTN.NTNGatewayLocation != nil {
		data.GatewayLocation = true
		data.GatewayLatitude = spec.NTN.NTNGatewayLocation.Latitude
		data.GatewayLongitude = spec.NTN.NTNGatewayLocation.Longitude
		data.GatewayAltitude = spec.NTN.NTNGatewayLocation.Altitude
	}
	if spec.NTN.MovingRefLocation != nil {
		data.MovingRefLocation = true
		data.MovingRefLatitude = spec.NTN.MovingRefLocation.Latitude
		data.MovingRefLongitude = spec.NTN.MovingRefLocation.Longitude
	}
	if spec.NTN.SatSwitchWithResync != nil {
		data.SatSwitchWithResync = true
		data.SatSwitchTargetPCI = spec.NTN.SatSwitchWithResync.TargetPCI
		data.SatSwitchT304 = spec.NTN.SatSwitchWithResync.T304
	}
	if spec.NTN.Polarization != nil {
		pol := spec.NTN.Polarization
		if pol.DL != "" || pol.UL != "" {
			data.HasPolarization = true
			data.PolarizationDL = pol.DL
			data.PolarizationUL = pol.UL
		}
	}
	if spec.NTN.TAReport != nil {
		data.TAReportSet = true
		data.TAReport = *spec.NTN.TAReport
	}
	if spec.NTN.NTNUlSyncValidityDur != nil {
		data.UlSyncValidityDurSet = true
		data.UlSyncValidityDur = *spec.NTN.NTNUlSyncValidityDur
	}
}

func applyStage3Fields(data *configData, spec *ntnv1alpha1.NTNCellConfigSpec) {
	if len(spec.NTN.NeighborCells) > 0 {
		data.HasNCells = true
		for _, nc := range spec.NTN.NeighborCells {
			data.NCells = append(data.NCells, ntnNeighborCellData{
				PhysicalCellID: nc.PhysicalCellID,
				Frequency:      nc.Frequency,
			})
		}
	}
	if spec.NTN.ReferenceLocation != nil {
		data.HasReferenceLocation = true
		data.RefLatitude = spec.NTN.ReferenceLocation.Latitude
		data.RefLongitude = spec.NTN.ReferenceLocation.Longitude
	}
	if spec.NTN.DistanceThreshold != nil {
		data.HasDistanceThreshold = true
		data.DistanceThreshold = *spec.NTN.DistanceThreshold
	}
	if spec.NTN.TService != nil {
		data.HasTService = true
		data.TService = *spec.NTN.TService
	}
}

func applyCellOverrides(data *configData, spec *ntnv1alpha1.NTNCellConfigSpec) {
	if spec.CellOverrides == nil {
		return
	}

	if spec.CellOverrides.PdschMaxHarqRetxs > 0 {
		data.PdschMaxHarqRetxs = spec.CellOverrides.PdschMaxHarqRetxs
	}
	if spec.CellOverrides.PrachMaxMsg3HarqRetx > 0 {
		data.PrachMaxMsg3HarqRetx = spec.CellOverrides.PrachMaxMsg3HarqRetx
	}
	if spec.CellOverrides.RrcGuardTimeMs > 0 {
		data.RrcGuardTimeMs = spec.CellOverrides.RrcGuardTimeMs
	}
	if sched := spec.CellOverrides.SIBSchedule; sched != nil {
		if sched.SIWindowLength > 0 {
			data.SIWindowLength = sched.SIWindowLength
		}
		if sched.SIPeriod > 0 {
			data.SIPeriod = sched.SIPeriod
		}
		if sched.SIWindowPosition != nil {
			data.SIWindowPosition = *sched.SIWindowPosition
		}
	}
}

func applyEphemeris(data *configData, spec *ntnv1alpha1.NTNCellConfigSpec) error {
	if spec.NTN.EphemerisECEF != nil && spec.NTN.EphemerisOrbital != nil {
		return fmt.Errorf("ephemerisECEF and ephemerisOrbital are mutually exclusive")
	}

	switch {
	case spec.NTN.EphemerisOrbital != nil:
		data.UseOrbital = true
		data.OrbSemiMajorAxis = spec.NTN.EphemerisOrbital.SemiMajorAxis
		data.OrbEccentricity = spec.NTN.EphemerisOrbital.Eccentricity
		data.OrbInclination = spec.NTN.EphemerisOrbital.Inclination
		data.OrbRightAscension = spec.NTN.EphemerisOrbital.RightAscension
		data.OrbArgOfPeriapsis = spec.NTN.EphemerisOrbital.ArgOfPeriapsis
		data.OrbMeanAnomaly = spec.NTN.EphemerisOrbital.MeanAnomaly
	case spec.NTN.EphemerisECEF != nil:
		data.EphPosX = spec.NTN.EphemerisECEF.PosX
		data.EphPosY = spec.NTN.EphemerisECEF.PosY
		data.EphPosZ = spec.NTN.EphemerisECEF.PosZ
		data.EphVelX = spec.NTN.EphemerisECEF.VelX
		data.EphVelY = spec.NTN.EphemerisECEF.VelY
		data.EphVelZ = spec.NTN.EphemerisECEF.VelZ
	default:
		return fmt.Errorf("either ephemerisECEF or ephemerisOrbital must be set")
	}

	return nil
}
