/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package ocudu

import (
	"bytes"
	"fmt"
	"text/template"

	ntnv1alpha1 "github.com/thc1006/ntn-operators/api/v1alpha1"
)

// configTemplate generates srsRAN/OCUDU-compatible NTN configuration YAML.
//
// This format was validated against srsRAN gNB commit 4bf1543 (OCUDU v1.0).
// Key format differences from the old docs-era geo_ntn.yml:
//   - ta_common is under ntn.ta_info (not ntn.ta_common)
//   - ephemeris uses ephemeris_info_ecef or ephemeris_orbital (variant)
//   - sib_mapping is scalar 19 (not array [19])
//   - si_window_position is REQUIRED for SIB19
//   - pucch.sr_period_ms is omitted (let gNB use bandwidth-appropriate default)
const configTemplate = `# Generated by NTN K8s Operators — do not edit manually
# Payload type: {{ .PayloadType }} (3GPP Rel-19: transparent or regenerative)

ntn:
  cell_specific_koffset: {{ .Koffset }}
  ta_info:
    ta_common: {{ .TACommon }}
{{- if .UseOrbital }}
  ephemeris_orbital:
    semi_major_axis: {{ .OrbSemiMajorAxis }}
    eccentricity: {{ .OrbEccentricity }}
    inclination: {{ .OrbInclination }}
    right_ascension: {{ .OrbRightAscension }}
    arg_of_periapsis: {{ .OrbArgOfPeriapsis }}
    mean_anomaly: {{ .OrbMeanAnomaly }}
{{- else }}
  ephemeris_info_ecef:
    pos_x: {{ .EphPosX }}
    pos_y: {{ .EphPosY }}
    pos_z: {{ .EphPosZ }}
    vel_x: {{ .EphVelX }}
    vel_y: {{ .EphVelY }}
    vel_z: {{ .EphVelZ }}
{{- end }}
{{- if .HasNCells }}
  ncells:
{{- range .NCells }}
    - phys_cell_id: {{ .PhysicalCellID }}
{{- if .Frequency }}
      frequency: {{ .Frequency }}
{{- end }}
{{- end }}
{{- end }}
{{- if .HasReferenceLocation }}
  reference_location:
    latitude: {{ .RefLatitude }}
    longitude: {{ .RefLongitude }}
{{- end }}
{{- if .HasDistanceThreshold }}
  distance_threshold: {{ .DistanceThreshold }}
{{- end }}
{{- if .HasTService }}
  t_service: {{ .TService }}
{{- end }}

cell_cfg:
  sib:
    si_window_length: 5
    si_sched_info:
      - si_period: 16
        sib_mapping: 19
        si_window_position: 1
  pdsch:
    max_nof_harq_retxs: {{ .PdschMaxHarqRetxs }}
  prach:
    max_msg3_harq_retx: {{ .PrachMaxMsg3HarqRetx }}

cu_cp:
  rrc:
    rrc_procedure_guard_time_ms: {{ .RrcGuardTimeMs }}
`

var parsedTemplate = template.Must(template.New("ocudu-ntn").Parse(configTemplate))

// ntnNeighborCellData holds per-neighbor data for template rendering.
type ntnNeighborCellData struct {
	PhysicalCellID int
	Frequency      int
}

type configData struct {
	PayloadType          string
	Koffset              int
	TACommon             int
	UseOrbital           bool
	EphPosX              int
	EphPosY              int
	EphPosZ              int
	EphVelX              int
	EphVelY              int
	EphVelZ              int
	OrbSemiMajorAxis     int
	OrbEccentricity      int
	OrbInclination       int
	OrbRightAscension    int
	OrbArgOfPeriapsis    int
	OrbMeanAnomaly       int
	PdschMaxHarqRetxs    int
	PrachMaxMsg3HarqRetx int
	RrcGuardTimeMs       int
	HasNCells            bool
	NCells               []ntnNeighborCellData
	HasReferenceLocation bool
	RefLatitude          int
	RefLongitude         int
	HasDistanceThreshold bool
	DistanceThreshold    int
	HasTService          bool
	TService             int
}

// GenerateConfig produces srsRAN/OCUDU-compatible NTN configuration YAML
// from an NTNCellConfigSpec. The output matches the CLI11 config format
// accepted by srsRAN gNB (verified against commit 4bf1543).
func GenerateConfig(spec *ntnv1alpha1.NTNCellConfigSpec) ([]byte, error) {
	if spec == nil {
		return nil, fmt.Errorf("spec must not be nil")
	}

	payloadType := spec.NTN.PayloadType
	if payloadType == "" {
		payloadType = "transparent"
	}

	data := configData{
		PayloadType:          payloadType,
		Koffset:              spec.NTN.CellSpecificKoffset,
		TACommon:             spec.NTN.TACommon,
		PdschMaxHarqRetxs:    0,
		PrachMaxMsg3HarqRetx: 0,
		RrcGuardTimeMs:       12800,
	}

	if spec.NTN.EphemerisECEF != nil && spec.NTN.EphemerisOrbital != nil {
		return nil, fmt.Errorf("ephemerisECEF and ephemerisOrbital are mutually exclusive")
	}

	switch {
	case spec.NTN.EphemerisOrbital != nil:
		data.UseOrbital = true
		data.OrbSemiMajorAxis = spec.NTN.EphemerisOrbital.SemiMajorAxis
		data.OrbEccentricity = spec.NTN.EphemerisOrbital.Eccentricity
		data.OrbInclination = spec.NTN.EphemerisOrbital.Inclination
		data.OrbRightAscension = spec.NTN.EphemerisOrbital.RightAscension
		data.OrbArgOfPeriapsis = spec.NTN.EphemerisOrbital.ArgOfPeriapsis
		data.OrbMeanAnomaly = spec.NTN.EphemerisOrbital.MeanAnomaly
	case spec.NTN.EphemerisECEF != nil:
		data.EphPosX = spec.NTN.EphemerisECEF.PosX
		data.EphPosY = spec.NTN.EphemerisECEF.PosY
		data.EphPosZ = spec.NTN.EphemerisECEF.PosZ
		data.EphVelX = spec.NTN.EphemerisECEF.VelX
		data.EphVelY = spec.NTN.EphemerisECEF.VelY
		data.EphVelZ = spec.NTN.EphemerisECEF.VelZ
	default:
		return nil, fmt.Errorf("either ephemerisECEF or ephemerisOrbital must be set")
	}

	// Map Stage 3 multi-cell NTN fields.
	if len(spec.NTN.NeighborCells) > 0 {
		data.HasNCells = true
		for _, nc := range spec.NTN.NeighborCells {
			data.NCells = append(data.NCells, ntnNeighborCellData{
				PhysicalCellID: nc.PhysicalCellID,
				Frequency:      nc.Frequency,
			})
		}
	}
	if spec.NTN.ReferenceLocation != nil {
		data.HasReferenceLocation = true
		data.RefLatitude = spec.NTN.ReferenceLocation.Latitude
		data.RefLongitude = spec.NTN.ReferenceLocation.Longitude
	}
	if spec.NTN.DistanceThreshold != nil {
		data.HasDistanceThreshold = true
		data.DistanceThreshold = *spec.NTN.DistanceThreshold
	}
	if spec.NTN.TService != nil {
		data.HasTService = true
		data.TService = *spec.NTN.TService
	}

	// Apply custom overrides if provided.
	if spec.CellOverrides != nil {
		if spec.CellOverrides.PdschMaxHarqRetxs > 0 {
			data.PdschMaxHarqRetxs = spec.CellOverrides.PdschMaxHarqRetxs
		}
		if spec.CellOverrides.PrachMaxMsg3HarqRetx > 0 {
			data.PrachMaxMsg3HarqRetx = spec.CellOverrides.PrachMaxMsg3HarqRetx
		}
		if spec.CellOverrides.RrcGuardTimeMs > 0 {
			data.RrcGuardTimeMs = spec.CellOverrides.RrcGuardTimeMs
		}
	}

	var buf bytes.Buffer
	if err := parsedTemplate.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("executing config template: %w", err)
	}

	return buf.Bytes(), nil
}
