/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package ocudu

import (
	"bytes"
	"fmt"
	"text/template"

	ntnv1alpha1 "github.com/thc1006/ntn-operators/api/v1alpha1"
)

// configTemplate generates OCUDU-compatible NTN configuration YAML
// matching the geo_ntn.yml format from srsRAN/OCUDU.
const configTemplate = `# Generated by NTN K8s Operators — do not edit manually
ntn:
  cell_specific_koffset: {{ .Koffset }}
  ta_common: {{ .TACommon }}
  ephemeris_info:
    pos_x: {{ .EphPosX }}
    pos_y: {{ .EphPosY }}
    pos_z: {{ .EphPosZ }}
    vel_x: {{ .EphVelX }}
    vel_y: {{ .EphVelY }}
    vel_z: {{ .EphVelZ }}

cell_cfg:
  sib:
    si_window_length: 5
    si_sched_info:
      - si_period: 16
        sib_mapping:
          - 19
  pucch:
    sr_period_ms: {{ .PucchSRPeriodMs }}
  csi:
    csi_rs_period: 80
  pdsch:
    max_nof_harq_retxs: {{ .PdschMaxHarqRetxs }}
  prach:
    max_msg3_harq_retx: {{ .PrachMaxMsg3HarqRetx }}

cu_cp:
  rrc:
    rrc_procedure_guard_time_ms: {{ .RrcGuardTimeMs }}
`

type configData struct {
	Koffset              int
	TACommon             int
	EphPosX              int
	EphPosY              int
	EphPosZ              int
	EphVelX              int
	EphVelY              int
	EphVelZ              int
	PucchSRPeriodMs      int
	PdschMaxHarqRetxs    int
	PrachMaxMsg3HarqRetx int
	RrcGuardTimeMs       int
}

// GenerateConfig produces OCUDU-compatible NTN configuration YAML from
// an NTNCellConfigSpec. The output matches the geo_ntn.yml format used
// by srsRAN/OCUDU gNB.
func GenerateConfig(spec *ntnv1alpha1.NTNCellConfigSpec) ([]byte, error) {
	data := configData{
		Koffset:  spec.NTN.CellSpecificKoffset,
		TACommon: spec.NTN.TACommon,
		EphPosX:  spec.NTN.EphemerisECEF.PosX,
		EphPosY:  spec.NTN.EphemerisECEF.PosY,
		EphPosZ:  spec.NTN.EphemerisECEF.PosZ,
		EphVelX:  spec.NTN.EphemerisECEF.VelX,
		EphVelY:  spec.NTN.EphemerisECEF.VelY,
		EphVelZ:  spec.NTN.EphemerisECEF.VelZ,
		// Defaults for NTN cell overrides.
		PucchSRPeriodMs:      320,
		PdschMaxHarqRetxs:    0,
		PrachMaxMsg3HarqRetx: 0,
		RrcGuardTimeMs:       12800,
	}

	// Apply custom overrides if provided.
	if spec.CellOverrides != nil {
		if spec.CellOverrides.PucchSRPeriodMs > 0 {
			data.PucchSRPeriodMs = spec.CellOverrides.PucchSRPeriodMs
		}
		if spec.CellOverrides.PdschMaxHarqRetxs > 0 {
			data.PdschMaxHarqRetxs = spec.CellOverrides.PdschMaxHarqRetxs
		}
		if spec.CellOverrides.PrachMaxMsg3HarqRetx > 0 {
			data.PrachMaxMsg3HarqRetx = spec.CellOverrides.PrachMaxMsg3HarqRetx
		}
		if spec.CellOverrides.RrcGuardTimeMs > 0 {
			data.RrcGuardTimeMs = spec.CellOverrides.RrcGuardTimeMs
		}
	}

	tmpl, err := template.New("ocudu-ntn").Parse(configTemplate)
	if err != nil {
		return nil, fmt.Errorf("parsing config template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("executing config template: %w", err)
	}

	return buf.Bytes(), nil
}
